### PR TITLE
Geocoder city lookup demo

### PR DESCRIPTION
**Pull request by loneil**
# Description
Trying out the geocoder lookup in the UI.
Not sure if this is what we want? It looks up street names too...
Putting on a draft PR so we can shop it around.

Adds ",BC" after each one too, not sure if we want that stripped off.

@parc-jason is checking if we can set it to just cities so no street names

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by parc-jason** [comment]
if we change addressString to localityName, that would probably be more applicable.  Not much we can do with minScore for something like Victoria.  It's just that there are too many hits that are very similar or where the locality is considered an alias (ie Highlands, Sooke, Oak Bay all have Victoria as a locality alias).  Dropping the minScore for doesn't matter because you don't get a hit until you get to Victori .  Are we going to add in coordinates and send store in the db?

**Comment by loneil** [comment]
Cool thanks. I'll change the lookup type.
Coords could be put in, depends on priorities.

**Comment by TimCsaky** [comment]
looks great. i guess if we want to return coordinates, the form should only submit a value that is found in the look up. ie it's not an open text field and it isnt possible to enter a city that wasnt found.

**Comment by loneil** [comment]
@parc-jason @TimCsaky let me know if this branch no longer applies since we're doing it in another one.

**Comment by jujaga** [comment]
Closing this PR as its commits have been integrated in PR #93 .

**Pull request closed without merging**
